### ISSUE TITLE
No blinking cursor in char input mode

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/asyncglk#12]
https://curiousdannii.github.io/parchment-testing/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FViolet.zblorb

> Calm down.  All you have to do is write a thousand words and everything will be fine.  And you have all day, except it's already noon.

Expected: A blinking cursor, to indicate that you should press a key to continue. (The blinking cursor appears on <https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FViolet.zblorb>.)

Actual: No blinking cursor; there's no on-screen visible thing to do here.

**Comment by curiousdannii** [comment]
The form at the beginning of [Bureaucracy](https://curiousdannii.github.io/parchment-testing/?story=https://eblong.com/infocom/gamefiles/bureaucracy-r116-s870602.z4) is now only the regular amount of nightmare, not the special nightmare it was before where you didn't even know which field you were meant to fill in. 😆
