### ISSUE TITLE
iOS screen layout incorrect while opening the keyboard

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/asyncglk#14]
In iOS Simulator (iPhone 13, iOS 15.2), go to the I/O --> Keyboard menu and disconnect the hardware keyboard. (This makes the virtual keyboard behave like it normally does on an iPhone, but you'll have to click on your screen in order to type.)

Navigate to https://curiousdannii.github.io/parchment-testing/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FViolet.zblorb

As the page launches, the virtual keyboard is not visible, and the game is in char input mode. Tap on the screen to open the virtual keyboard, then tap on the space key.

At this point, the screen dimensions look wrong. Text flows off the right margin, and the window is scrolled all the way at the top of the screen. If you try to scroll down to read the rest of the page, it will instantly scroll you back up to the top, so you can't read the rest of the page.

![Simulator Screen Shot - iPhone 13 - 2022-01-24 at 15 04 26](https://user-images.githubusercontent.com/96150/150879724-5fc2300a-2713-4e55-a587-e6fae17465ab.png)

**Comment by dfabulich** [comment]
At this point, even refreshing the page won't make the problem go away, but, surprisingly, you can temporarily fix the screen by dismissing the keyboard and pinch zooming out. The bug re-occurs when you re-open the keyboard though, so it's no real help.

**Comment by curiousdannii** [comment]
I did enable pinch zooming as you encouraged. Does any similar issue occur with zooming on a physical device?

I think I might have seen a scrolling issue on my Android phone. I should add visualViewport.scale checks to all the scrolling code.

But if I'm understanding this, is the issue that when it focuses the input it automatically zooms so the input fills the width? This sort of thing is why I hadn't wanted to enabled zooming 😆.

**Comment by dfabulich** [comment]
Yes, I think that's what's happening. It's zooming in when focusing the text field. (Note that the body text gets a teeny tiny eensy weensy bit larger in the second screenshot.)

![Simulator Screen Shot - iPhone 13 - 2022-01-24 at 15 13 46](https://user-images.githubusercontent.com/96150/150880772-1b1541de-ab55-4c3a-a1c9-bb0f2532dae2.png)
![Simulator Screen Shot - iPhone 13 - 2022-01-24 at 15 13 53](https://user-images.githubusercontent.com/96150/150880774-6d457d85-05bf-4bea-8d37-aafa0b16c71a.png)

**Comment by curiousdannii** [comment]
[This SO page](https://stackoverflow.com/q/2989263/2854284) suggests two things:

1. Set the viewport meta to `maximum-scale=1` (would that then prevent Android from pinch zooming?)
2. Raise the buffer window font from 15px to 16px

I don't think I want to do the second, raising the font size would reduce the line character count too much.

I'll try the first. If it does prevent zooming in Android then I'll try what [this answer](https://stackoverflow.com/a/62750441/2854284) says to change the viewport meta only in iOS.

**Comment by dfabulich** [comment]
I believe `maximum-scale` is designed to prevent zooming, but I thought iOS would ignore it. https://stackoverflow.com/questions/46826411/new-ios-start-to-ignore-meta-viewport-maximum-scale-for-device-width

**Comment by curiousdannii** [comment]
I think this is fixed now. If there are any further issues let me know.
